config/routes.rb
Rails.application.routes.draw do
  resources :periodos

  resources :personas

  resources :cursos

  resources :carreras

  resources :aula_labs

  resources :recintos

  resources :horarios

end

app/models/carrera.rb
class Carrera < ActiveRecord::Base
end

app/controllers/carreras_controller.rb
class CarrerasController < ApplicationController
  before_action :set_carrera, only: [:show, :edit, :update, :destroy]

  # GET /carreras
  # GET /carreras.json
  def index
    @carreras = Carrera.all
  end

  # GET /carreras/1
  # GET /carreras/1.json
  def show
  end

  # GET /carreras/new
  def new
    @carrera = Carrera.new
  end

  # GET /carreras/1/edit
  def edit
  end

  # POST /carreras
  # POST /carreras.json
  def create
    @carrera = Carrera.new(carrera_params)

    respond_to do |format|
      if @carrera.save
        format.html { redirect_to @carrera, notice: 'Carrera was successfully created.' }
        format.json { render :show, status: :created, location: @carrera }
      else
        format.html { render :new }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carreras/1
  # PATCH/PUT /carreras/1.json
  def update
    respond_to do |format|
      if @carrera.update(carrera_params)
        format.html { redirect_to @carrera, notice: 'Carrera was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrera }
      else
        format.html { render :edit }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carreras/1
  # DELETE /carreras/1.json
  def destroy
    @carrera.destroy
    respond_to do |format|
      format.html { redirect_to carreras_url, notice: 'Carrera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrera
      @carrera = Carrera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrera_params
      params.require(:carrera).permit(:descripcion)
    end
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/views/carreras/_form.html.erb
<%= form_for(@carrera) do |f| %>
  <% if @carrera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrera.errors.count, "error") %> prohibited this carrera from being saved:</h2>

      <ul>
      <% @carrera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carreras/edit.html.erb
<h1>Editing carrera</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrera %> |
<%= link_to 'Back', carreras_path %>

app/views/carreras/index.html.erb
<h1>Listing carreras</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carreras.each do |carrera| %>
      <tr>
        <td><%= carrera.descripcion %></td>
        <td><%= link_to 'Show', carrera %></td>
        <td><%= link_to 'Edit', edit_carrera_path(carrera) %></td>
        <td><%= link_to 'Destroy', carrera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrera', new_carrera_path %>

app/views/carreras/new.html.erb
<h1>New carrera</h1>

<%= render 'form' %>

<%= link_to 'Back', carreras_path %>

app/views/carreras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @carrera.descripcion %>
</p>

<%= link_to 'Edit', edit_carrera_path(@carrera) %> |
<%= link_to 'Back', carreras_path %>