config/routes.rb
Rails.application.routes.draw do
  resources :periodos

  resources :personas

  resources :cursos

  resources :carreras

  resources :aula_labs

  resources :recintos

  resources :horarios

end

app/models/aula_lab.rb
class AulaLab < ActiveRecord::Base
end

app/controllers/aula_labs_controller.rb
class AulaLabsController < ApplicationController
  before_action :set_aula_lab, only: [:show, :edit, :update, :destroy]

  # GET /aula_labs
  # GET /aula_labs.json
  def index
    @aula_labs = AulaLab.all
  end

  # GET /aula_labs/1
  # GET /aula_labs/1.json
  def show
  end

  # GET /aula_labs/new
  def new
    @aula_lab = AulaLab.new
  end

  # GET /aula_labs/1/edit
  def edit
  end

  # POST /aula_labs
  # POST /aula_labs.json
  def create
    @aula_lab = AulaLab.new(aula_lab_params)

    respond_to do |format|
      if @aula_lab.save
        format.html { redirect_to @aula_lab, notice: 'Aula lab was successfully created.' }
        format.json { render :show, status: :created, location: @aula_lab }
      else
        format.html { render :new }
        format.json { render json: @aula_lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aula_labs/1
  # PATCH/PUT /aula_labs/1.json
  def update
    respond_to do |format|
      if @aula_lab.update(aula_lab_params)
        format.html { redirect_to @aula_lab, notice: 'Aula lab was successfully updated.' }
        format.json { render :show, status: :ok, location: @aula_lab }
      else
        format.html { render :edit }
        format.json { render json: @aula_lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aula_labs/1
  # DELETE /aula_labs/1.json
  def destroy
    @aula_lab.destroy
    respond_to do |format|
      format.html { redirect_to aula_labs_url, notice: 'Aula lab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula_lab
      @aula_lab = AulaLab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aula_lab_params
      params.require(:aula_lab).permit(:recintos, :descripcion, :observacion, :personas)
    end
end

app/helpers/aula_labs_helper.rb
module AulaLabsHelper
end

app/views/aula_labs/_form.html.erb
<%= form_for(@aula_lab) do |f| %>
  <% if @aula_lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aula_lab.errors.count, "error") %> prohibited this aula_lab from being saved:</h2>

      <ul>
      <% @aula_lab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recintos %><br>
    <%= f.text_field :recintos %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :observacion %><br>
    <%= f.text_field :observacion %>
  </div>
  <div class="field">
    <%= f.label :personas %><br>
    <%= f.text_field :personas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aula_labs/edit.html.erb
<h1>Editing aula_lab</h1>

<%= render 'form' %>

<%= link_to 'Show', @aula_lab %> |
<%= link_to 'Back', aula_labs_path %>

app/views/aula_labs/index.html.erb
<h1>Listing aula_labs</h1>

<table>
  <thead>
    <tr>
      <th>Recintos</th>
      <th>Descripcion</th>
      <th>Observacion</th>
      <th>Personas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aula_labs.each do |aula_lab| %>
      <tr>
        <td><%= aula_lab.recintos %></td>
        <td><%= aula_lab.descripcion %></td>
        <td><%= aula_lab.observacion %></td>
        <td><%= aula_lab.personas %></td>
        <td><%= link_to 'Show', aula_lab %></td>
        <td><%= link_to 'Edit', edit_aula_lab_path(aula_lab) %></td>
        <td><%= link_to 'Destroy', aula_lab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aula lab', new_aula_lab_path %>

app/views/aula_labs/new.html.erb
<h1>New aula_lab</h1>

<%= render 'form' %>

<%= link_to 'Back', aula_labs_path %>

app/views/aula_labs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recintos:</strong>
  <%= @aula_lab.recintos %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @aula_lab.descripcion %>
</p>

<p>
  <strong>Observacion:</strong>
  <%= @aula_lab.observacion %>
</p>

<p>
  <strong>Personas:</strong>
  <%= @aula_lab.personas %>
</p>

<%= link_to 'Edit', edit_aula_lab_path(@aula_lab) %> |
<%= link_to 'Back', aula_labs_path %>