config/routes.rb
Rails.application.routes.draw do
  resources :periodos

  resources :personas

  resources :cursos

  resources :carreras

  resources :aula_labs

  resources :recintos

  resources :horarios

end

app/models/persona.rb
class Persona < ActiveRecord::Base
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :estado, :celular, :correo, :contrasena, :carreras, :cursos, :perfil, :tipo_usuario)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.check_box :estado %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :contrasena %><br>
    <%= f.text_field :contrasena %>
  </div>
  <div class="field">
    <%= f.label :carreras %><br>
    <%= f.text_field :carreras %>
  </div>
  <div class="field">
    <%= f.label :cursos %><br>
    <%= f.text_field :cursos %>
  </div>
  <div class="field">
    <%= f.label :perfil %><br>
    <%= f.text_field :perfil %>
  </div>
  <div class="field">
    <%= f.label :tipo_usuario %><br>
    <%= f.text_field :tipo_usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<h1>Listing personas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Estado</th>
      <th>Celular</th>
      <th>Correo</th>
      <th>Contrasena</th>
      <th>Carreras</th>
      <th>Cursos</th>
      <th>Perfil</th>
      <th>Tipo usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.estado %></td>
        <td><%= persona.celular %></td>
        <td><%= persona.correo %></td>
        <td><%= persona.contrasena %></td>
        <td><%= persona.carreras %></td>
        <td><%= persona.cursos %></td>
        <td><%= persona.perfil %></td>
        <td><%= persona.tipo_usuario %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @persona.estado %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @persona.celular %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @persona.correo %>
</p>

<p>
  <strong>Contrasena:</strong>
  <%= @persona.contrasena %>
</p>

<p>
  <strong>Carreras:</strong>
  <%= @persona.carreras %>
</p>

<p>
  <strong>Cursos:</strong>
  <%= @persona.cursos %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @persona.perfil %>
</p>

<p>
  <strong>Tipo usuario:</strong>
  <%= @persona.tipo_usuario %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>